[package]
name = "raycaster_rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#beryllium = "0.12.2"
sdl2 = "0.35.2"
vector2d = "2.2.0"